SHOW USER;

CREATE TABLE TB_DEPARTMENT
(
    DEPARTMENT_NO VARCHAR2(10) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(20) NOT NULL,
    CATEGDRY VARCHAR2(20),
    OPEN_YN CHAR(1),
    CAPACITY NUMBER
);

 COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NO IS '학과 번호';
