-- 3일차
-- DDL(Data Definition Language) = 데이터 정의어
-- DDL의 종류 : CREATE, ALTER, DROP           
-- ex) CREATE USER, CREATE TABLE, DROP TABLE, ...
-- ALTER을 이용
-- 컬럼추가, 컬럼삭제, 컬럼수정(데이터타입, 이름), 테이블명 수정 2가지
-- 제약조건 추가, 삭제, 수정

DESC USER_FOREIGN_KEY;
-- ex01) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼을 추가
ALTER TABLE USER_FOREIGN_KEY
ADD USER_DATE DATE;
-- ex02) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼을 삭제
ALTER TABLE USER_FOREIGN_KEY
DROP COLUMN USER_DATE;
-- ex03) USER_FOREIGN_KEY 테이블에 REG_DATE 컬럼의 자료형을 VARCHAR2(10)으로 변경
ALTER TABLE USER_FOREIGN_KEY MODIFY USER_DATE VARCHAR2(10);
-- ex04) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼의 이름을 USER_DATE로 변경
ALTER TABLE USER_FOREIGN_KEY 
RENAME COLUMN REG_DATE TO USER_DATE;
-- ex05) USER_DATE의 VARCHAR2(10)를 DATE로 변경
ALTER TABLE USER_FOREIGN_KEY MODIFY USER_DATE DATE;
-- ex06) USER_FOREIGN_KEY 테이블의 이름을 USER_TBL로 변경 (2가지)
ALTER TABLE USER_FOREIGN_KEY
RENAME TO USER_TBL;

SELECT * FROM USER_TBL;
DESC USER_TBL;

-- 제약 조건 추가, 삭제, 수정
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_TBL';

-- 제약 조건 이름 변경
ALTER TABLE USER_TBL
RENAME CONSTRAINT SYS_C007163 TO FK_GRADE_CODE;

-- 제약 조건 삭제
ALTER TABLE USER_TBL
DROP CONSTRAINT FK_GRADE_CODE;

-- 제약 조건 추가
ALTER TABLE USER_TBL
ADD FOREIGN KEY(GRADE_CODE) REFERENCES USER_GRADE(GRADE_CODE);

-- NOT NULL 추가, 제약 조건명을 따로 설정하지 않음
ALTER TABLE USER_TBL
MODIFY USER_ID NOT NULL;
DESC USER_TBL;

ALTER TABLE USER_TBL
MODIFY USER_DATE DEAULT SYSDATE;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_TBL';

-- CONSTRAINT FK_GRADE_CODE 이름 설정하기
ALTER TABLE USER_TBL
ADD CONSTRAINT FK_GRADE_CODE 
-- 제약조건 외래키 추가
FOREIGN KEY(GRADE_CODE) REFERENCES USER_GRADE(GRADE_CODE);
-- 출력 > Table USER_TBL이(가) 변경되었습니다.
-- 1. 실행하면 ROW 1개 ROW
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_TBL';
-- 2. CONTAINT_NAME이 FK_GRADE_CODE인 것 확인

-- USER_GRADE가 가지고 있는 제약 조건 조회하여 삭제 후 같은 이름으로 설정
-- 조회
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_GRADE';
-- 제약 조건 이름 변경
ALTER TABLE USER_GRADE
RENAME CONSTRAINT PK_GRADE_CODE TO FK_GRADE_CODE;
-- 삭제
ALTER TABLE USER_GRADE
DROP CONSTRAINT FK_GRADE_CODE;
-- 재생성
ALTER TABLE USER_GRADE
ADD CONSTRAINT FK_GRADE_CODE PRIMARY KEY(GRADE_CODE);

-- 제약 조건 활성화/비활성화
ALTER TABLE USER_TBL
DISABLE CONSTRAINT FK_GRADE_CODE;
ALTER TABLE USER_TBL
ENABLE CONSTRAINT FK_GRADE_CODE;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_TBL';

DROP TABLE USER_TBL;














