-- 집합 연산자
-- UNION : A∪B, 중복 미허용
-- UNION ALL : A + B, 중복 허용
-- INTERSECT : A∩B, 교집합
-- MINUS : A - A∩B

-- < 합집합 >
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;

SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL -- 중복 허용
SELECT EMP_NAME, TO_NUMBER(EMP_ID) FROM EMPLOYEE
WHERE SALARY >= 2400000;

-- 컬럼갯수 같고 컬럼이 데이터타입이 각각 같아야 함

-- < 교집합 >
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
MINUS
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;